#*******************************************************************************
#.appveyor.yml
#*******************************************************************************

#Purpose:
#AppVeyor is a hosted continuous integration service, that is, it allows running
#code directly from a repository and checking that the code acts as expected. 
#The purpose of the .appveyor.yml file is to give instructions to AppVeyor on
#how to do the work.
#Author:
#Cedric H. David, 2018-2018


#*******************************************************************************
#System specifications for AppVeyor
#*******************************************************************************
version: 1.0.{build}

build: false

image:
  - Visual Studio 2015


branches:
  only:
    - master
    - exp  

#*******************************************************************************
#Environment variables for different tests on multiple AppVeyor workers
#*******************************************************************************
environment:
  matrix:
    - TST_PUB_DWNL: 'tst_pub_dwnl_David_etal_201x_SER.sh'
      TST_PUB_REPR: 'tst_pub_repr_David_etal_201x_SER.sh'
  
      EARTH_USERNAME:
        secure: iJJA/KDq2f5V3/k8IRSHHA==

      EARTH_PASSWORD:
        secure: goH0K33745ArR1LCelFXeQ==


#init:
#  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

#*******************************************************************************
#Before installing SHBAAM
#*******************************************************************************
install:
  - ps: echo "machine urs.earthdata.nasa.gov" > ~/.netrc 
  - ps: echo "login $env:EARTH_USERNAME" >> ~/.netrc
  - ps: echo "password $env:EARTH_PASSWORD" >> ~/.netrc
  - ps: rm Alias:wget
  - ps: choco install --no-progress ((gc requirements.cho) -notmatch '^#' -match '\S')
  - ps: $ENV:PATH="C:\\ProgramData\\MiniConda2;C:\\ProgramData\\MiniConda2\\Scripts;$ENV:PATH"
  - ps: $ENV:PATH="C:\\Program Files (x86)\\GnuWin32\\bin;$ENV:PATH"


#*******************************************************************************
#Installing SHBAAM
#*******************************************************************************
build_script:
  - ps: conda install -y -q -c anaconda --file requirements.cnd


#*******************************************************************************
#Testing SHBAAM
#*******************************************************************************
test_script:
  - ps: ls ~/
  - ps: cat ~/.netrc
  - ps: cd tst
  - ps: Write-Host $env:TST_PUB_DWNL
  - ps: bash $env:TST_PUB_DWNL
  - ps: Write-Host $env:TST_PUB_REPR
  - ps: bash $env:TST_PUB_REPR


on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

#*******************************************************************************
#End
#*******************************************************************************
